### ISSUE TITLE
1.18? not really an issue, just a request

### ISSUE THREAD

**Issue by pastelalien** [Hi-ImKyle/anvilformat#1]
Hi! I don't mean to bother, but I couldn't get this mod to work in my 1.18.2 pack. I tried both files, but either returned an error looking for the corresponding game version. Again, I don't mean to push, and feel free to ignore this if you want, but if you could make a 1.18 build, I would very much appreciate it. Thanks! Hope you're having a nice day!

**Comment by Hi-ImKyle** [comment]
Hey sorry for the absence, took a little internet detox. 

I built it for 1.7-1.18 targeting either as a broad version check and it seemed to work in testing but if something has changed _somehow_, I don't mind taking a look as I do need to build a 1.19.X version too.

Can you just give me a screenshot of the error/prompt? I'll get to working on it within a week or so.

**Comment by Hi-ImKyle** [comment]
Just to be clear the 1.17-1.18 builds are on CurseForge [here](https://www.curseforge.com/minecraft/mc-mods/anvil-format)
